version: 1.0
provider:
  name: openfaas

functions:
  go-long:
    lang: golang-middleware
    handler: ./go-long
    image: ghcr.io/${OWNER:-openfaas}/go-long:${TAG:-latest}
    environment:
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s

  node12-sleep:
    lang: node12
    handler: ./node12-sleep
    image: ghcr.io/${OWNER:-openfaas}/node12-long:${TAG:-latest}
    environment:
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m

configuration:
  templates:
  - name: golang-middleware
  - name: node12

